var winnings=parseFloat(localStorage.getItem("winnings")),winHistory=localStorage.getItem("winHistory"),trackLocation=localStorage.getItem("trackLocation"),winHistoryImport,currentDate=new Date(),latitude,longitude,currentLocation,geocoder,previousWinnings,winCountCycle=1,winCountIncrement,winCountInterval,itemToDelete;if(!winnings){winnings=0;}
if(winHistory){winHistoryImport=winHistory.split(',');var tempWinHistory=[];var historyLenght=winHistoryImport.length;for(var i=0;historyLenght>i;i=i+4){var importAmount=parseFloat(winHistoryImport[i]);var importDate=winHistoryImport[i+1];if(winHistoryImport[i+2]=='false'){var importLatitude=false;}else{var importLatitude=winHistoryImport[i+2];}
if(winHistoryImport[i+3]=='false'){var importLongitude=false;}else{var importLongitude=winHistoryImport[i+3];}
tempWinHistory.push([importAmount,importDate,importLatitude,importLongitude]);};winHistory=tempWinHistory;}else{winHistory=[];}
function supports_html5_storage(){try{return 'localStorage'in window&&window['localStorage']!==null;}catch(e){return false;}}
function updateWinnings(amount){winCountIncrement=(winnings-previousWinnings)/10;localStorage.setItem("winnings",winnings.toFixed(2));$('#amount').val('');var seconds=currentDate.getSeconds();if(seconds<10)seconds='0'+seconds;var timeStamp=currentDate.getDate()+'/'+(currentDate.getMonth()+1)+'/'+currentDate.getFullYear()+' - '+currentDate.getHours()+':'+currentDate.getMinutes()+':'+seconds;winHistory.push([amount.toFixed(2),timeStamp,latitude,longitude]);localStorage.setItem("winHistory",winHistory);$('html,body').animate({scrollTop:$("#currentWinningsPanel").offset().top-10},50);winCountInterval=setInterval(winCounter,50);}
function winCounter(){if(winCountCycle==10){clearInterval(winCountInterval);winCountCycle=1;$('#currentWinnings').text('$'+winnings.toFixed(2));}else{var winCounterNumber=previousWinnings+(winCountIncrement*winCountCycle);$('#currentWinnings').text('$'+winCounterNumber.toFixed(2));winCountCycle=winCountCycle+1;}}
function locationSuccess(position){latitude=position.coords.latitude;longitude=position.coords.longitude;currentLocation=codeLatLng(latitude,longitude);}
function locationFail(){latitude=false;longitude=false;}
function codeLatLng(lat,lng){var latlng=new google.maps.LatLng(lat,lng);geocoder.geocode({'latLng':latlng},function(results,status){if(status==google.maps.GeocoderStatus.OK){if(results[1]){$("#currentLocation").html('<h3>Current Location</h3><p>'+results[0].formatted_address+'</p>');return results[0].formatted_address;}else{return false;}}else{return false;}});}
function generateHistory(){if(winHistory.length==0){$('#history').append('<p>You curently have nothing in your history.</p>');}else{$('#history').html('');for(var i=winHistory.length-1;i>=0;i--){$('#history').append('<div class="historyItem" id="historyItem'+i+'"></div>');var historyItem=winHistory[i];if(historyItem[0]>0){$('#historyItem'+i).append('<h3 class="green">Won: $'+historyItem[0]+'</h3>');}else{$('#historyItem'+i).append('<h3 class="red">Lost: $'+historyItem[0]+'</h3>');}
$('#historyItem'+i).append('<p>Date: '+historyItem[1]+'</p>');if(historyItem[2]){$('#historyItem'+i).append('<p><a href="http://maps.google.com/?q='+historyItem[2]+','+historyItem[3]+'" target="_blank">Location</a></p>');}else{$('#historyItem'+i).append('<p>Location not available.</p>');}
$('#historyItem'+i).append('<p><a href="#" class="removeHistoryItem" id="'+i+'">Remove this item</a></p>');};$('.removeHistoryItem').click(function(){itemToDelete=parseInt($(this).attr('id'));$("#removeHistoryPopup").popup("open");});}}
function restSavedData(){winnings=0;winHistory=[];localStorage.setItem("winnings",winnings);localStorage.setItem("winHistory",winHistory);$('#currentWinnings').text('$'+winnings.toFixed(2));}
function deleteItem(){winnings=winnings-winHistory[itemToDelete][0];$('#currentWinnings').text('$'+winnings.toFixed(2));localStorage.setItem("winnings",winnings.toFixed(2));winHistory.splice(itemToDelete,1);localStorage.setItem("winHistory",winHistory);generateHistory();}
$(document).on('pageshow','#historyPage',function(){generateHistory();});$(document).on('pageshow','#settings',function(){$('#geolocation').val('on').slider('refresh');});$(document).ready(function(){if(supports_html5_storage()){$('#currentWinnings').text('$'+winnings);}else{$('#currentWinnings').text('Your browser does not support local storage');}
geocoder=new google.maps.Geocoder();if(navigator.geolocation){navigator.geolocation.getCurrentPosition(locationSuccess,locationFail);}else{locationFail();}
$('#won').click(function(){if($('#amount').val()!=""){previousWinnings=winnings;var amount=parseFloat($('#amount').val());winnings=winnings+amount;updateWinnings(amount);}});$('#lost').click(function(){if($('#amount').val()!=""){previousWinnings=winnings;var amount=parseFloat($('#amount').val());if(amount>0){winnings=winnings-amount;}else{winnings=winnings+amount;};updateWinnings(0-amount);}});$('#cancelRemoveHistory').click(function(){$("#removeHistoryPopup").popup("close");});$('#confirmRemoveHistory').click(function(){deleteItem();$("#removeHistoryPopup").popup("close");});$('#deleteSavedData').click(function(){$("#deleteSavedDataPopup").popup("open");});$('#cancelDeleteSavedData').click(function(){$("#deleteSavedDataPopup").popup("close");});$('#confirmDeleteSavedData').click(function(){restSavedData();$("#deleteSavedDataPopup").popup("close");});$('#geolocationYes').click(function(){trackLocation='yes';$("#welcomeScreen").popup("close");});$('#geolocationNo').click(function(){trackLocation='no';$("#welcomeScreen").popup("close");});});